theme: jekyll-theme-minimal
title: Andreas Zeller
description: Andreas Zeller is faculty at the [CISPA Helholtz Center for Information Security](https://www.cispa.saarland) and professor for Software Engineering at [Saarland University](https://www.cs.uni-saarland.de/).
logo: Zeller09-full.jpg