theme: jekyll-theme-minimal
title: Samuel Ferino
layout: default
plugins:
    - jekyll-optional-front-matter
    - jekyll-redirect-from
    - jekyll-feed
include:
    - README.md
optional_front_matter:
  remove_originals: true
defaults:
  - scope:
      path: "*.md"
    values:
      layout: default
tagline: PhD candidate at Monash University
twitter:
    - username: samuellucas97
social:
  links:
    - https://www.linkedin.com/in/samuel1797
description: Samuel Ferino does software research on Human-AI for Software Engineering at Monash University
bio: Samuel Ferino is a PhD candidate at   
    <a href="https://www.monash.edu" target=_blank>Monash University</a>, in Melbourne/Australia. He is supervised by Prof. <a href="https://rashina.com" target=_blank>Rashina Hoda</a>, Prof. <a href="https://sites.google.com/site/johncgrundy" target=_blank>John Grundy</a>, and Associate Prof. <a href="https://ctreude.ca/" target=_blank>Christoph Treude</a>.
    He is also member of <a href=" https://www.monash.edu/it/humanise-lab" target=_blank>HumaniSE Lab</a>.
  

    <p>
    <i class="fa fa-envelope-o fa-fw" aria-hidden="true" title="Mail"></i>
    <span class="sr-only">Mail:</span><a href="mailto:samuel.demouraferino@monash.edu" title="Mail">samuel.demouraferino@monash.edu</a> <br>
    <i class="fa fa-linkedin fa-fw" aria-hidden="true" title="Linkedin"></i>
    <span class="sr-only">Linkedin:</span>&nbsp;&nbsp;<a rel="me noopener"  href="https://www.linkedin.com/in/samuel1797" title="Linkedin" target="_blank">@samuel1797</a> <br>
    <!-- <i class="fa fa-twitter fa-fw" aria-hidden="true" title="Twitter"></i> -->
    <!-- adapted from https://fontawesomeicons.com/fa/twitter-x-logo -->
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="-2 -2 31 24" version="1.1" height="1em">
            <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z" fill="#767676"></path>
    </svg>
    <span class="sr-only">Twitter:</span>&nbsp;&nbsp;<a href="https://www.twitter.com/samuellucas97" title="Twitter" target="_blank">@samuellucas97</a> <br>
    <i class="fa fa-github fa-fw" aria-hidden="true" title="GitHub"></i>
        <span class="sr-only">GitHub:</span>&nbsp;&nbsp;<a href="https://github.com/Samuellucas97" title="GitHub" target="_blank">Samuellucas97</a>
logo: assets/Samuel2024-head.jpeg
logo_title: Samuel Ferino (high resolution photo)
