theme: jekyll-theme-minimal
title: Andreas Zeller
layout: default
plugins:
    - jekyll-optional-front-matter
    - jekyll-redirect-from
include:
    - README.md
optional_front_matter:
  remove_originals: true
defaults:
  - scope:
      path: "*.md"
    values:
      layout: default
tagline: Software research at CISPA and Saarland University
twitter:
    - username: AndreasZeller
social:
  links:
    - https://twitter.com/AndreasZeller
description: Andreas Zeller does software research on automated debugging, mining software archives, specification mining, and security testing at CISPA and Saarland University
bio: Andreas Zeller is faculty at the 
    <a href="https://www.cispa.de" target=_blank>CISPA Helmholtz Center for Information Security</a> and professor for Software Engineering at 
    <a href="https://saarland-informatics-campus.de/en/" target=_blank>Saarland University</a>, both in Saarbrücken, Germany.  
    His <a href="https://scholar.google.com/citations?user=-Qytr_YAAAAJ&hl=en&oi=ao" target=_blank>research</a> 
    on automated debugging, mining software archives, specification mining, and security testing has proven <a href="/assets/ZellerCV.pdf">highly influential</a>.  
    Zeller is an <a href="https://awards.acm.org/fellows" target=_blank>ACM Fellow</a> and holds an <a href="https://www.sigsoft.org/awards/outstandingResearchAward.html" target=_blank>ACM SIGSOFT Outstanding Research Award</a>.<p>
    <i class="fa fa-envelope-o" aria-hidden="true"></i>
    <span class="sr-only">Mail:</span>&nbsp;&nbsp;<a href="mailto:zeller@cispa.de">zeller@cispa.de</a><br>
    <i class="fa fa-phone" aria-hidden="true"></i>
    <span class="sr-only">Phone:</span>&nbsp;&nbsp;<a href="tel:+49681870832372">+49 681 87083-2372</a><br>
    <i class="fa fa-twitter" aria-hidden="true"></i>
    <span class="sr-only">Twitter:</span>&nbsp;&nbsp;<a href="https://www.twitter.com/AndreasZeller">@AndreasZeller</a>
logo: assets/Zeller09-full.jpg
logo_title: Andreas Zeller (high resolution photo)
